import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/modules/header/components/Header";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ModalProvider from "@/components/providers/ModalProvider";
import { MapControlsProvider } from "@/modules/map/components/providers/MapControlsProvider";

const font = Poppins({
  weight: ["400", "600", "800"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Padel - Find game near to you",
  description: "Generated by Amel for his client.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} flex flex-col bg-body lg:!h-[100dvh]`}
      >
        <ThemeProvider>
          <ModalProvider />
          <Header />
          <MapControlsProvider>{children}</MapControlsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
